title: My blog - Wharley Ornelas
email: wharleyornelasjs@gmail.com
description: > #this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wharley.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Wharley Ornelas # add your name
author-pic: wharley-face.jpg
about-author: Meu nome é Wharley Ornelas. Desenvolvedor Full-Stack, com mais de 15 anos de experiência de software. Membro ativo em comunidade de desenvolvimento..

# Contact links
email: wharleyornelasjs@gmail.com # Add your Email address
phone: (31) 988960511 # Add your Phone number
website: # Add your website, do not add http://
linkedin: wharley-ornelas-da-rocha-65420932 # Add your Linkedin handle
github: wharley # Add your Github handle
twitters: '@wharleyornelas' # Add your Twitter handle\
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: wharleyornelas # Add your MailChimp form identifier.

# Disqus
discus_identifier: wharleyornelas-com # Add your discus identifier

# Tracker
analytics: UA-114382847-1 # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-twitter-plugin

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
